- name: Add the user 'your_username' with a specific uid and a primary group of 'admin,sudo' and generate a generate_ssh_key
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ user_password }}"
    comment: for example your name
    uid: 1005 
    groups: admin,sudo
    create_home: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
