---
- hosts: all
  become_user: root

  tasks:
    - name: allow ssh # example port 22
      community.general.ufw:
        rule: allow
        port: 22
        proto: tcp
        src: 192.168.178.0/24 # example

    - name: ssh limit
      community.general.ufw:
        rule: limit # limit limit of five incorrect registrations
        port: ssh
        proto: tcp

    - name: allow https
      community.general.ufw: 
        rule: allow
        port: https
        proto: tcp


